# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jiaotong404/demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jiaotong404/demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiaotong404/demo/CMakeFiles /home/jiaotong404/demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jiaotong404/demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named osqp_demo

# Build rule for target.
osqp_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osqp_demo
.PHONY : osqp_demo

# fast build rule for target.
osqp_demo/fast:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/build
.PHONY : osqp_demo/fast

osqp_demo.o: osqp_demo.cc.o

.PHONY : osqp_demo.o

# target to build an object file
osqp_demo.cc.o:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_demo.cc.o
.PHONY : osqp_demo.cc.o

osqp_demo.i: osqp_demo.cc.i

.PHONY : osqp_demo.i

# target to preprocess a source file
osqp_demo.cc.i:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_demo.cc.i
.PHONY : osqp_demo.cc.i

osqp_demo.s: osqp_demo.cc.s

.PHONY : osqp_demo.s

# target to generate assembly for a file
osqp_demo.cc.s:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_demo.cc.s
.PHONY : osqp_demo.cc.s

osqp_problem.o: osqp_problem.cc.o

.PHONY : osqp_problem.o

# target to build an object file
osqp_problem.cc.o:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_problem.cc.o
.PHONY : osqp_problem.cc.o

osqp_problem.i: osqp_problem.cc.i

.PHONY : osqp_problem.i

# target to preprocess a source file
osqp_problem.cc.i:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_problem.cc.i
.PHONY : osqp_problem.cc.i

osqp_problem.s: osqp_problem.cc.s

.PHONY : osqp_problem.s

# target to generate assembly for a file
osqp_problem.cc.s:
	$(MAKE) -f CMakeFiles/osqp_demo.dir/build.make CMakeFiles/osqp_demo.dir/osqp_problem.cc.s
.PHONY : osqp_problem.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... osqp_demo"
	@echo "... edit_cache"
	@echo "... osqp_demo.o"
	@echo "... osqp_demo.i"
	@echo "... osqp_demo.s"
	@echo "... osqp_problem.o"
	@echo "... osqp_problem.i"
	@echo "... osqp_problem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

